// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Trivial round-trip command used to prove the IPC + typed-bindings wiring (M0). */
	ping: () => __TAURI_INVOKE<string>("ping"),
	/**  Derive the required-asset list for a config. Pure — no persistence. */
	deriveAssets: (config: GameConfig) => __TAURI_INVOKE<AssetDescriptor[]>("derive_assets", { config }),
	/**  Create a new project. Errors if one with the same id already exists. */
	createProject: (config: GameConfig) => typedError<Project, string>(__TAURI_INVOKE("create_project", { config })),
	/**
	 *  Delete a game and everything under it — assets, takes, studio docs, exports.
	 *  Guarded: only removes a folder that actually contains a `project.json`.
	 */
	deleteProject: (gameId: string) => typedError<null, string>(__TAURI_INVOKE("delete_project", { gameId })),
	/**  Save a config for an existing project, or create it if new. Preserves `created_at`. */
	saveProjectConfig: (config: GameConfig) => typedError<Project, string>(__TAURI_INVOKE("save_project_config", { config })),
	/**  Load one project by id. */
	getProject: (gameId: string) => typedError<Project, string>(__TAURI_INVOKE("get_project", { gameId })),
	/**  List all projects (summaries), newest-updated first. */
	listProjects: () => typedError<ProjectSummary[], string>(__TAURI_INVOKE("list_projects")),
	/**  The absolute projects root, for display in the UI. */
	projectsRootPath: () => typedError<string, string>(__TAURI_INVOKE("projects_root_path")),
	/**  Store the OpenAI API key in the OS keychain (used for gpt-image-1). Empty clears it. */
	setOpenaiKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("set_openai_key", { key })),
	/**  Whether an OpenAI key is configured (for cloud image generation). */
	openaiKeyPresent: () => __TAURI_INVOKE<boolean>("openai_key_present"),
	/**  Store the Gemini API key ("Nano Banana"). Empty clears it. */
	setGeminiKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("set_gemini_key", { key })),
	/**  Whether a Gemini key is configured. */
	geminiKeyPresent: () => __TAURI_INVOKE<boolean>("gemini_key_present"),
	/**  Store the SpriteCook API key (`sc_live_…`). Empty clears it. */
	setSpritecookKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("set_spritecook_key", { key })),
	/**  Whether a SpriteCook key is configured. */
	spritecookKeyPresent: () => __TAURI_INVOKE<boolean>("spritecook_key_present"),
	/**  Store the Gamelab Studio API key. Empty clears it. */
	setGamelabKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("set_gamelab_key", { key })),
	/**  Whether a Gamelab Studio key is configured. */
	gamelabKeyPresent: () => __TAURI_INVOKE<boolean>("gamelab_key_present"),
	/**
	 *  Generate an AI spritesheet for the asset's active PROCESSED image via SpriteCook.
	 *  `frames` is clamped to the detailed-mode range (2–24, even).
	 */
	generateAiSheet: (gameId: string, assetKey: string, prompt: string, frames: number) => typedError<AiSheet, string>(__TAURI_INVOKE("generate_ai_sheet", { gameId, assetKey, prompt, frames })),
	/**  The saved AI sheet for an asset, if any. */
	getAiSheet: (gameId: string, assetKey: string) => typedError<{
	/**  Sheet PNG as a data URL (for immediate preview). */
	dataUrl: string,
	frames: number,
	width: number,
	height: number,
	prompt: string,
} | null, string>(__TAURI_INVOKE("get_ai_sheet", { gameId, assetKey })),
	/**  Load an asset's record, returning a fresh empty one if it doesn't exist yet. */
	getAssetRecord: (gameId: string, assetKey: string) => typedError<AssetRecord, string>(__TAURI_INVOKE("get_asset_record", { gameId, assetKey })),
	/**  List all existing asset records for a project. */
	listAssetRecords: (gameId: string) => typedError<AssetRecord[], string>(__TAURI_INVOKE("list_asset_records", { gameId })),
	/**  Save an asset's subject / overrides. */
	savePrompt: (gameId: string, assetKey: string, subject: string, overridePrompt: string, negativeOverride: string, layered: boolean) => typedError<AssetRecord, string>(__TAURI_INVOKE("save_prompt", { gameId, assetKey, subject, overridePrompt, negativeOverride, layered })),
	/**
	 *  Assemble the final prompt from the (live) config + the given subject/overrides.
	 *  Pure — reflects unsaved config edits too.
	 */
	assemblePrompt: (config: GameConfig, assetKey: string, subject: string, overridePrompt: string, negativeOverride: string, layered: boolean) => typedError<AssembledPrompt, string>(__TAURI_INVOKE("assemble_prompt", { config, assetKey, subject, overridePrompt, negativeOverride, layered })),
	/**
	 *  Seed a starting `subject` for every raster asset that has none yet (symbols draw
	 *  from their config description; others from the descriptor). Deterministic, no API.
	 *  Returns the number seeded.
	 */
	seedSubjects: (gameId: string) => typedError<number, string>(__TAURI_INVOKE("seed_subjects", { gameId })),
	/**  Brainstorm reply for a conversation (non-streaming). */
	assistantChat: (messages: ChatMessage[]) => typedError<string, string>(__TAURI_INVOKE("assistant_chat", { messages })),
	/**
	 *  Streaming brainstorm: emits `assistant://chunk` events with token deltas as they
	 *  arrive, and returns the full reply when done.
	 */
	assistantChatStream: (messages: ChatMessage[]) => typedError<string, string>(__TAURI_INVOKE("assistant_chat_stream", { messages })),
	/**  Draft a full config from the conversation, merged over the current config. */
	assistantFillConfig: (messages: ChatMessage[], current: GameConfig) => typedError<GameConfig, string>(__TAURI_INVOKE("assistant_fill_config", { messages, current })),
	/**  A copyable prompt for filling the blueprint in an EXTERNAL agent (no API key needed). */
	configDraftPrompt: (current: GameConfig) => __TAURI_INVOKE<string>("config_draft_prompt", { current }),
	/**  Apply a config JSON pasted back from an external agent, merged over the current config. */
	applyConfigJson: (current: GameConfig, json: string) => typedError<GameConfig, string>(__TAURI_INVOKE("apply_config_json", { current, json })),
	/**  Current non-secret app settings. */
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	/**  Persist app settings. */
	saveSettings: (settings: AppSettings) => typedError<null, string>(__TAURI_INVOKE("save_settings", { settings })),
	/**  List the available image providers and whether each is configured. */
	listImageProviders: () => typedError<ProviderInfo[], string>(__TAURI_INVOKE("list_image_providers")),
	/**
	 *  Generate new variation(s) for an asset. `count` (1–4) requests run CONCURRENTLY —
	 *  cloud providers handle parallel calls fine, and four takes at once is how you pick
	 *  a best. If the asset already has an active variation, each new one records it as
	 *  its `parent` (lineage). Returns the updated record; errors only when EVERY request
	 *  failed.
	 */
	generateVariation: (gameId: string, assetKey: string, providerId: string, referenceKeys: string[], guideKey: string, count: number) => typedError<AssetRecord, string>(__TAURI_INVOKE("generate_variation", { gameId, assetKey, providerId, referenceKeys, guideKey, count })),
	/**
	 *  Assemble the sheet prompt for the selected symbols WITHOUT generating — the composer
	 *  shows it for review; the user may override it wholesale.
	 */
	planSymbolSet: (gameId: string, assetKeys: string[]) => typedError<SetPlan, string>(__TAURI_INVOKE("plan_symbol_set", { gameId, assetKeys })),
	/**
	 *  Generate ONE sheet of the selected symbols and hold it as PENDING — nothing is cut
	 *  yet. Returns the preview plus the detected cut seams so the user can judge both the
	 *  art AND the split before committing. Calling again (reroll) replaces the pending
	 *  sheet. `prompt_override` non-empty → used verbatim instead of the assembled prompt.
	 */
	generateSymbolSetSheet: (gameId: string, assetKeys: string[], providerId: string, promptOverride: string, referenceKeys: string[]) => typedError<SetSheet, string>(__TAURI_INVOKE("generate_symbol_set_sheet", { gameId, assetKeys, providerId, promptOverride, referenceKeys })),
	/**
	 *  Use the user's OWN image as the pending sheet — same review/seams/commit flow as a
	 *  generated one, no provider involved. Background handling is detected from the
	 *  image: real alpha → native, magenta border → chroma, anything else → opaque
	 *  (rembg keys each cut cell later, exactly like a single-symbol import).
	 */
	importSymbolSetSheet: (gameId: string, assetKeys: string[], path: string) => typedError<SetSheet, string>(__TAURI_INVOKE("import_symbol_set_sheet", { gameId, assetKeys, path })),
	/**
	 *  Manual override for the pending sheet's cut: change the grid (seams re-detect for
	 *  the new shape) or pin exact seam positions (fractions 0–1, from dragging the lines
	 *  in the preview). Persisted into the pending meta, so Commit cuts exactly this.
	 *  Pass empty seam vecs to re-detect; pass full vecs (cols−1 / rows−1 entries) to pin.
	 */
	adjustSymbolSet: (gameId: string, cols: number, rows: number, seamsX: (number | null)[], seamsY: (number | null)[]) => typedError<SetSheet, string>(__TAURI_INVOKE("adjust_symbol_set", { gameId, cols, rows, seamsX, seamsY })),
	/**
	 *  Cut the pending sheet along the detected seams, upscale each cell to working
	 *  resolution, and land every cell as its symbol's new ACTIVE variation. The normal
	 *  Process pass handles keying + the fit pass per symbol afterwards.
	 */
	commitSymbolSet: (gameId: string) => typedError<AssetRecord[], string>(__TAURI_INVOKE("commit_symbol_set", { gameId })),
	/**
	 *  Manually erase areas of a take to transparency: the frontend paints an erase mask
	 *  (white = remove) over the take's best image; the result lands as a NEW active
	 *  variation with native alpha. The manual fallback for cut-outs and stray backdrop
	 *  remnants the automatic keying missed.
	 */
	alphaErase: (gameId: string, assetKey: string, variationId: string, maskB64: string) => typedError<AssetRecord, string>(__TAURI_INVOKE("alpha_erase", { gameId, assetKey, variationId, maskB64 })),
	/**
	 *  Generate (or regenerate) the game's style anchor with the given provider.
	 *  A non-empty `override_prompt` is used verbatim as the positive (the anchor's
	 *  anti-slop negative floor still applies). Returns a data URL for immediate preview.
	 */
	generateStyleAnchor: (gameId: string, providerId: string, overridePrompt: string) => typedError<string, string>(__TAURI_INVOKE("generate_style_anchor", { gameId, providerId, overridePrompt })),
	/**
	 *  The auto-assembled anchor prompt (style master + calibration-plate composition) —
	 *  shown editable in the UI so the user can customise before generating.
	 */
	styleAnchorPrompt: (gameId: string) => typedError<string, string>(__TAURI_INVOKE("style_anchor_prompt", { gameId })),
	/**  The current style anchor as a data URL, or `None` if the game has no anchor. */
	getStyleAnchor: (gameId: string) => typedError<string | null, string>(__TAURI_INVOKE("get_style_anchor", { gameId })),
	/**  Whether the game has a style anchor (cheap presence check for the bench chip). */
	styleAnchorPresent: (gameId: string) => typedError<boolean, string>(__TAURI_INVOKE("style_anchor_present", { gameId })),
	/**  Use an existing image file as the style anchor (normalised to PNG, ≤1024 long side). */
	importStyleAnchor: (gameId: string, path: string) => typedError<string, string>(__TAURI_INVOKE("import_style_anchor", { gameId, path })),
	/**  Remove the style anchor — generations stop referencing it. */
	removeStyleAnchor: (gameId: string) => typedError<null, string>(__TAURI_INVOKE("remove_style_anchor", { gameId })),
	/**
	 *  Import an existing image file as a new (active) variation — the "bring your own source"
	 *  entry into the pipeline. Normalises to PNG and detects transparency. No prompt/generation.
	 */
	importSourceImage: (gameId: string, assetKey: string, path: string) => typedError<AssetRecord, string>(__TAURI_INVOKE("import_source_image", { gameId, assetKey, path })),
	/**
	 *  Upscale a variation to a NEW active variation (original kept). `method`:
	 *  - `"api"` → gpt-image-2 faithful high-res recreation (uses the OpenAI key).
	 *  - anything else → local free: Real-ESRGAN if installed, otherwise Lanczos, to `target_long`.
	 *  Preserves the source's background mode so a later Process still keys/handles it correctly.
	 */
	upscaleVariation: (gameId: string, assetKey: string, variationId: string, targetLong: number, method: string) => typedError<AssetRecord, string>(__TAURI_INVOKE("upscale_variation", { gameId, assetKey, variationId, targetLong, method })),
	/**
	 *  Targeted revision of a variation via gpt-image-2 edits: apply ONE described change,
	 *  keep everything else. Saved as a NEW active variation with lineage (reroll stays
	 *  available — this is sculpting, not gambling). Transparent/native raws are flattened
	 *  onto magenta first so the result always rides the chroma post-processing path.
	 */
	refineVariation: (gameId: string, assetKey: string, variationId: string, instruction: string) => typedError<AssetRecord, string>(__TAURI_INVOKE("refine_variation", { gameId, assetKey, variationId, instruction })),
	/**  Mark a variation as the active one for an asset. */
	setActiveVariation: (gameId: string, assetKey: string, variationId: string) => typedError<AssetRecord, string>(__TAURI_INVOKE("set_active_variation", { gameId, assetKey, variationId })),
	/**
	 *  Delete one variation from an asset's history: removes it from the record and deletes its
	 *  on-disk files. If it was the active one, the most recent remaining variation becomes active
	 *  (or none, if the history is now empty).
	 */
	deleteVariation: (gameId: string, assetKey: string, variationId: string) => typedError<AssetRecord, string>(__TAURI_INVOKE("delete_variation", { gameId, assetKey, variationId })),
	/**  Lock or unlock a variation. Locked variations are protected from `delete_variation`. */
	setVariationLocked: (gameId: string, assetKey: string, variationId: string, locked: boolean) => typedError<AssetRecord, string>(__TAURI_INVOKE("set_variation_locked", { gameId, assetKey, variationId, locked })),
	/**
	 *  Mark an asset as template-only (e.g. an `l_base` empty plate other symbols compose
	 *  onto). Template assets are excluded from Export and Publish — they never ship.
	 */
	setTemplateOnly: (gameId: string, assetKey: string, templateOnly: boolean) => typedError<AssetRecord, string>(__TAURI_INVOKE("set_template_only", { gameId, assetKey, templateOnly })),
	/**  Read a variation's raw image as a `data:image/png;base64,…` URL for display. */
	getVariationImage: (gameId: string, assetKey: string, variationId: string) => typedError<string, string>(__TAURI_INVOKE("get_variation_image", { gameId, assetKey, variationId })),
	/**  Audit one variation of an asset. Cheap enough to run on every Finish. */
	assetQuality: (gameId: string, assetKey: string, variationId: string) => typedError<QualityReport, string>(__TAURI_INVOKE("asset_quality", { gameId, assetKey, variationId })),
	/**
	 *  Compose every symbol at TRUE cell pixel size into the actual grid, over a flat
	 *  dark field — judging symbols at 1024 px against white is exactly how scale
	 *  problems survive to production. Labels/boxes are drawn by the UI as overlays.
	 */
	symbolContactSheet: (gameId: string) => typedError<ContactSheet, string>(__TAURI_INVOKE("symbol_contact_sheet", { gameId })),
	/**  Report which external post-processing tools are available. */
	preflight: () => __TAURI_INVOKE<Preflight>("preflight"),
	/**  Run the post-processing pipeline for one variation, producing shippable finals. */
	processVariation: (gameId: string, assetKey: string, variationId: string) => typedError<AssetRecord, string>(__TAURI_INVOKE("process_variation", { gameId, assetKey, variationId })),
	/**  Read one of a variation's processed stage files as a data URL. */
	getVariationStageImage: (gameId: string, assetKey: string, variationId: string, stageName: string) => typedError<string, string>(__TAURI_INVOKE("get_variation_stage_image", { gameId, assetKey, variationId, stageName })),
	/**
	 *  Build the dist tree + manifest snippet for a game (ASSETS.md §16/§17). Rebuilds from
	 *  scratch and reports which assets were written vs. still missing a processed variation.
	 */
	exportDist: (gameId: string) => typedError<ExportReport, string>(__TAURI_INVOKE("export_dist", { gameId })),
	/**
	 *  Copy READY assets' processed finals into `dest_dir`: `<asset_key>.webp` plus its
	 *  secondary twin — `.png` for alpha assets, `.jpg` for opaque ones (backgrounds,
	 *  scene plates, splash) — the "drop straight into the game repo" step. Existing files
	 *  of the same name are overwritten. When `keys` is non-empty only those assets are
	 *  considered (else every asset). Remembers `dest_dir` for one-click re-publish.
	 */
	publishFinals: (gameId: string, destDir: string, keys: string[]) => typedError<PublishReport, string>(__TAURI_INVOKE("publish_finals", { gameId, destDir, keys })),
	/**
	 *  Open (or create) the studio for an asset. On first open the active processed variation
	 *  is snapshotted to `studio/source.png` and a degenerate single-part doc with a canned
	 *  "idle" breathe clip is seeded — immediately previewable and exportable.
	 */
	studioOpen: (gameId: string, assetKey: string) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_open", { gameId, assetKey })),
	/**  Persist the doc (stamps `updatedAt`). */
	studioSave: (gameId: string, assetKey: string, doc: StudioDoc) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_save", { gameId, assetKey, doc })),
	/**
	 *  Re-snapshot `source.png` from the current active processed variation. Keeps the rest of
	 *  the doc; masks/cuts may become stale (the source hash changes, invalidating caches).
	 */
	studioReimportSource: (gameId: string, assetKey: string) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_reimport_source", { gameId, assetKey })),
	/**  Read a file under the asset's studio dir as a data URL (source, masks, cuts…). */
	studioGetImage: (gameId: string, assetKey: string, rel: string) => typedError<string, string>(__TAURI_INVOKE("studio_get_image", { gameId, assetKey, rel })),
	/**  Build the preview bundle for a (possibly unsaved) doc — same emit+pack as export. */
	studioPreviewBundle: (gameId: string, assetKey: string, doc: StudioDoc) => typedError<PreviewBundle, string>(__TAURI_INVOKE("studio_preview_bundle", { gameId, assetKey, doc })),
	/**
	 *  Fast path for keyframe editing: emit ONLY the skeleton JSON (same emitter as export),
	 *  so the frontend can reuse its cached atlas/textures. ~ms instead of re-encoding pages.
	 */
	studioSkeletonOnly: (doc: StudioDoc) => typedError<string, string>(__TAURI_INVOKE("studio_skeleton_only", { doc })),
	/**  Save the doc, then write the Spine export set to `studio/export/`. */
	studioExport: (gameId: string, assetKey: string, doc: StudioDoc) => typedError<StudioExportReport, string>(__TAURI_INVOKE("studio_export", { gameId, assetKey, doc })),
	/**  Is a local SAM model available (and which tier)? */
	studioSamStatus: () => typedError<SamStatus, string>(__TAURI_INVOKE("studio_sam_status")),
	/**
	 *  Download SAM weights (`hq` = full ViT-B ~375 MB, else MobileSAM ~40 MB), emitting
	 *  `studio://sam-progress` events.
	 */
	studioSamDownload: (hq: boolean) => typedError<SamStatus, string>(__TAURI_INVOKE("studio_sam_download", { hq })),
	/**  Ask gpt-4o vision for a part plan (names + SAM seed points) for this asset's source. */
	studioProposeParts: (gameId: string, assetKey: string, hint: string) => typedError<PartProposal[], string>(__TAURI_INVOKE("studio_propose_parts", { gameId, assetKey, hint })),
	/**
	 *  Region-first auto cut: SAM segments the whole source into candidate regions (grid
	 *  sweep, real boundaries), gpt-4o only LABELS them into named parts (no coordinate
	 *  guessing). Replaces the doc's parts with the labeled plan and persists their masks.
	 */
	studioAutoCut: (gameId: string, assetKey: string, hint: string) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_auto_cut", { gameId, assetKey, hint })),
	/**
	 *  Run SAM with the given click prompts against this asset's source and return the
	 *  refined candidate mask. Pure preview — nothing is persisted.
	 */
	studioSegment: (gameId: string, assetKey: string, prompts: SamPrompt[]) => typedError<MaskResult, string>(__TAURI_INVOKE("studio_segment", { gameId, assetKey, prompts })),
	/**
	 *  Cloud "paint-out" cut: gpt-image-2 repaints EVERYTHING except the named part as one
	 *  flat magenta field; keying the result yields the part's mask. Slower and paid
	 *  (~10–30 s, cents per call) versus local SAM, but the model understands semantics
	 *  ("the left cable", "the glow behind the crown"), which can beat point-prompted
	 *  segmentation on hard art. Returns a candidate mask — same preview/apply flow as SAM.
	 */
	studioCloudCut: (gameId: string, assetKey: string, partId: string) => typedError<MaskResult, string>(__TAURI_INVOKE("studio_cloud_cut", { gameId, assetKey, partId })),
	/**
	 *  Persist a part's mask (from an accepted SAM result or manual brush work) and the
	 *  prompts that produced it. The mask must be a full-source-size gray PNG data URL.
	 */
	studioSetMask: (gameId: string, assetKey: string, partId: string, maskDataUrl: string, prompts: SamPrompt[]) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_set_mask", { gameId, assetKey, partId, maskDataUrl, prompts })),
	/**  Cut all masked parts from the original pixels and rebuild the static skeleton. */
	studioCutParts: (gameId: string, assetKey: string) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_cut_parts", { gameId, assetKey })),
	/**
	 *  Auto-rig the cut parts: mask analysis (adjacency, PCA, joint bands) in Rust; the parent
	 *  tree from gpt-4o when a key is set, else a pure heuristic. Replaces `doc.bones`.
	 */
	studioAutoRig: (gameId: string, assetKey: string) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_auto_rig", { gameId, assetKey })),
	/**  Per-part occlusion/inpaint state (clear / pending / fresh / stale). */
	studioInpaintStatus: (gameId: string, assetKey: string) => typedError<InpaintStatus[], string>(__TAURI_INVOKE("studio_inpaint_status", { gameId, assetKey })),
	/**  Inpaint one part's hidden band. `force` regenerates even on a cache hit. */
	studioInpaintPart: (gameId: string, assetKey: string, partId: string, force: boolean) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_inpaint_part", { gameId, assetKey, partId, force })),
	/**
	 *  Inpaint every stale/pending occluded part (bounded concurrency), emitting
	 *  `studio://inpaint-progress` events per part.
	 */
	studioInpaintAll: (gameId: string, assetKey: string) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_inpaint_all", { gameId, assetKey })),
	/**
	 *  Draft a keyframe clip from a text brief over the current skeleton. Returns the clip
	 *  only — the frontend decides whether/where to apply it (cheap reroll, one-shot revert).
	 */
	studioAiDraftClip: (gameId: string, assetKey: string, name: string, brief: string) => typedError<Clip, string>(__TAURI_INVOKE("studio_ai_draft_clip", { gameId, assetKey, name, brief })),
	/**
	 *  AI breakdown keys between two times of a clip. Takes the clip from the frontend
	 *  (unsaved edits included) and returns the updated clip.
	 */
	studioAiInbetween: (gameId: string, assetKey: string, clip: Clip, fromTime: number | null, toTime: number | null, count: number) => typedError<Clip, string>(__TAURI_INVOKE("studio_ai_inbetween", { gameId, assetKey, clip, fromTime, toTime, count })),
	/**
	 *  Toggle a part between a rigid region and a deformable auto-weighted mesh. Enabling
	 *  (re)generates the mesh from the part's CURRENT texture, so re-running after an inpaint
	 *  or recut refreshes it.
	 */
	studioSetMesh: (gameId: string, assetKey: string, partId: string, enabled: boolean) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_set_mesh", { gameId, assetKey, partId, enabled })),
	/**
	 *  Save baked clip frames (PNG data URLs from the real runtime) as a spritesheet +
	 *  metadata under `studio/export/sheets/` — the fallback for non-Spine consumers.
	 */
	studioSaveSpritesheet: (gameId: string, assetKey: string, clip: string, fps: number, frames: string[]) => typedError<string, string>(__TAURI_INVOKE("studio_save_spritesheet", { gameId, assetKey, clip, fps, frames })),
	/**
	 *  Generate a light-effect layer with gpt-image-2: the effect is painted in place over
	 *  the symbol on PURE BLACK (black = invisible under additive blending), luminance
	 *  becomes alpha, and the result lands as an ordinary part on an ADDITIVE slot with its
	 *  own bone — animatable, physics-able, reorderable like any other part.
	 */
	studioGenerateFx: (gameId: string, assetKey: string, name: string, brief: string) => typedError<StudioDoc, string>(__TAURI_INVOKE("studio_generate_fx", { gameId, assetKey, name, brief })),
	/**
	 *  Open (or create) the parallax layers for an asset. On first open the active processed
	 *  variation is snapshotted to `layers/source.png` and a 4-band doc is seeded
	 *  (sky catch-all / far / mid / foreground).
	 */
	layersOpen: (gameId: string, assetKey: string) => typedError<LayersDoc, string>(__TAURI_INVOKE("layers_open", { gameId, assetKey })),
	/**  Persist the doc (rename / reorder / speeds / add / delete flow through here). */
	layersSave: (gameId: string, assetKey: string, doc: LayersDoc) => typedError<LayersDoc, string>(__TAURI_INVOKE("layers_save", { gameId, assetKey, doc })),
	/**
	 *  Re-snapshot `source.png` from the current active processed variation (after a new
	 *  concept was approved). Masks/cuts/fills go stale via the source-hash change.
	 */
	layersReimportSource: (gameId: string, assetKey: string) => typedError<LayersDoc, string>(__TAURI_INVOKE("layers_reimport_source", { gameId, assetKey })),
	/**  Read a file under the asset's layers dir as a data URL (source, masks, cuts, fills…). */
	layersGetImage: (gameId: string, assetKey: string, rel: string) => typedError<string, string>(__TAURI_INVOKE("layers_get_image", { gameId, assetKey, rel })),
	/**  Ask gpt-4o vision for a depth-band plan (count layers, farthest first, seed points). */
	layersPropose: (gameId: string, assetKey: string, count: number, hint: string) => typedError<LayerProposal[], string>(__TAURI_INVOKE("layers_propose", { gameId, assetKey, count, hint })),
	/**  Whether the depth-estimation model weights are on disk. */
	layersDepthStatus: () => typedError<DepthStatus, string>(__TAURI_INVOKE("layers_depth_status")),
	/**
	 *  Download the depth-estimation weights (~190 MB total), emitting
	 *  `layers://depth-progress` events.
	 */
	layersDepthDownload: () => typedError<DepthStatus, string>(__TAURI_INVOKE("layers_depth_download")),
	/**
	 *  Propose layers from ESTIMATED DEPTH: run Depth Anything V2 over the scene, slice the
	 *  depth map into `count` bands (far → near), and rebuild the doc with one layer per band
	 *  — selections come from actual depth, not object guessing. Replaces all existing layers
	 *  and their selections/cuts/fills.
	 */
	layersProposeDepth: (gameId: string, assetKey: string, count: number) => typedError<LayersDoc, string>(__TAURI_INVOKE("layers_propose_depth", { gameId, assetKey, count })),
	/**
	 *  Run SAM with the given click prompts against this asset's scene and return the refined
	 *  candidate selection. Pure preview — nothing is persisted. Unlike the studio variant,
	 *  large enclosed openings (arches, canopy gaps) are NOT filled.
	 */
	layersSegment: (gameId: string, assetKey: string, prompts: SamPrompt[]) => typedError<MaskResult, string>(__TAURI_INVOKE("layers_segment", { gameId, assetKey, prompts })),
	/**
	 *  Cloud "paint-out" cut for a depth layer: gpt-image-2 repaints everything except the
	 *  named band/element as flat magenta; keying yields the layer mask. The semantic
	 *  option for backgrounds where depth bands and click-prompted SAM struggle.
	 */
	layersCloudCut: (gameId: string, assetKey: string, layerId: string) => typedError<MaskResult, string>(__TAURI_INVOKE("layers_cloud_cut", { gameId, assetKey, layerId })),
	/**
	 *  Persist a layer's selection (accepted SAM result or manual brush work) and the prompts
	 *  that produced it. Must be a full-source-size gray PNG data URL. Not valid for the
	 *  catch-all layer (index 0) — its claim is derived.
	 */
	layersSetMask: (gameId: string, assetKey: string, layerId: string, maskDataUrl: string, prompts: SamPrompt[]) => typedError<LayersDoc, string>(__TAURI_INVOKE("layers_set_mask", { gameId, assetKey, layerId, maskDataUrl, prompts })),
	/**
	 *  Trace a layer's selection into simplified, editable polygon rings (outer boundaries
	 *  and holes; closed implicitly). `tolerance` is the simplification strength in source px.
	 */
	layersTraceOutline: (gameId: string, assetKey: string, layerId: string, tolerance: number | null) => typedError<(([(number | null), (number | null)])[])[], string>(__TAURI_INVOKE("layers_trace_outline", { gameId, assetKey, layerId, tolerance })),
	/**  Cut all layers from the approved pixels (exclusive claim; layer 0 takes the rest). */
	layersCut: (gameId: string, assetKey: string) => typedError<LayersDoc, string>(__TAURI_INVOKE("layers_cut", { gameId, assetKey })),
	/**  Per-layer fill state (clear / pending / fresh / stale). */
	layersFillStatus: (gameId: string, assetKey: string) => typedError<FillStatus[], string>(__TAURI_INVOKE("layers_fill_status", { gameId, assetKey })),
	/**
	 *  Fill hidden bands. `only` limits to one layer; `force` regenerates even on a cache hit
	 *  (this is the per-layer "regenerate without touching the others" path). Emits
	 *  `layers://fill-progress` events per layer.
	 */
	layersFill: (gameId: string, assetKey: string, only: string | null, force: boolean) => typedError<LayersDoc, string>(__TAURI_INVOKE("layers_fill", { gameId, assetKey, only, force })),
	/**  Write the export set: one full-dims alpha WebP per layer + `parallax.json`. */
	layersExport: (gameId: string, assetKey: string) => typedError<LayersExportReport, string>(__TAURI_INVOKE("layers_export", { gameId, assetKey })),
	/**  Every glyph in the cross-game library, newest first. */
	glyphList: () => typedError<GlyphInfo[], string>(__TAURI_INVOKE("glyph_list")),
	/**  A glyph's shape as a data URL (white fill, alpha = the mark). */
	glyphImage: (glyphId: string) => typedError<string, string>(__TAURI_INVOKE("glyph_image", { glyphId })),
	/**
	 *  Generate a glyph shape from a prompt and save it to the library. When `glyph_id` is
	 *  non-empty an existing glyph is regenerated in place (same id, new shape + prompt);
	 *  otherwise a new id is derived from the prompt.
	 */
	glyphGenerate: (prompt: string, providerId: string, glyphId: string) => typedError<GlyphInfo, string>(__TAURI_INVOKE("glyph_generate", { prompt, providerId, glyphId })),
	/**
	 *  Import an image file as a glyph shape (secondary path). Any raster format works —
	 *  the same shape extraction runs on it (native alpha or flat background).
	 */
	glyphImport: (name: string, path: string) => typedError<GlyphInfo, string>(__TAURI_INVOKE("glyph_import", { name, path })),
	/**
	 *  Remove a glyph from the library (assets referencing it keep their prompt and can
	 *  simply regenerate).
	 */
	glyphDelete: (glyphId: string) => typedError<null, string>(__TAURI_INVOKE("glyph_delete", { glyphId })),
	/**  This asset's saved glyph settings, if it has any. */
	glyphGet: (gameId: string, assetKey: string) => typedError<{
	/**  Asset key whose current best image is the shared template. */
	baseAsset: string,
	/**  What to draw on it — the glyph generation prompt. */
	prompt: string,
	/**  Library shape backing this mark, once generated. */
	glyphId?: string | null,
	transform: Transform,
	params: EmbossParams,
} | null, string>(__TAURI_INVOKE("glyph_get", { gameId, assetKey })),
	/**  Persist the asset's glyph settings (base choice, prompt, placement, emboss). */
	glyphSave: (gameId: string, assetKey: string, glyph: AssetGlyph) => typedError<null, string>(__TAURI_INVOKE("glyph_save", { gameId, assetKey, glyph })),
	/**  Compose in memory (nothing written) — the live preview while placing/tuning. */
	glyphPreview: (gameId: string, glyph: AssetGlyph) => typedError<ComposedPreview, string>(__TAURI_INVOKE("glyph_preview", { gameId, glyph })),
	/**
	 *  Compose and write the result as this asset's new ACTIVE variation (provider
	 *  `glyphs`), with `glyph_mask.png` beside the raw on the same canvas — the alpha the
	 *  game engine uses for win-glow. Also persists the glyph settings.
	 */
	glyphCompose: (gameId: string, assetKey: string, glyph: AssetGlyph) => typedError<AssetRecord, string>(__TAURI_INVOKE("glyph_compose", { gameId, assetKey, glyph })),
};

/* Types */
/**  Result of an AI-sheet run, persisted next to the asset. */
export type AiSheet = {
	/**  Sheet PNG as a data URL (for immediate preview). */
	dataUrl: string,
	frames: number,
	width: number,
	height: number,
	prompt: string,
};

export type AppSettings = {
	/**  Base URL of the local Draw Things / A1111-compatible HTTP server. */
	drawThingsUrl?: string,
	/**  OpenAI image model id. */
	openaiImageModel?: string,
	/**  Gemini image model id (Nano Banana 2; use gemini-3-pro-image-preview for the Pro tier). */
	geminiImageModel?: string,
	/**  SpriteCook generation model id. */
	spritecookModel?: string,
	/**  OpenAI vision model used for part proposals / region labeling. */
	openaiVisionModel?: string,
	/**
	 *  Absolute path to the folder that holds project folders. Empty = default
	 *  (`<app_data_dir>/projects`). Lets projects live inside a repo or on an SSD.
	 */
	projectsRoot?: string,
};

/**  The assembled prompt actually sent to a provider — for live preview in the UI. */
export type AssembledPrompt = {
	positive: string,
	negative: string,
};

/**
 *  A single concrete asset the game needs, derived from `GameConfig`. This is the unit
 *  the asset grid renders and the generation/processing/export stages operate on.
 */
export type AssetDescriptor = {
	/**  Stable key, e.g. `symbol_h1`, `bg_base_landscape`, `reel_frame`. */
	key: string,
	kind: AssetKind,
	/**  Dist subdirectory (ASSETS.md §16), e.g. `backgrounds`, `reel_chrome`, `panels`. */
	category: string,
	/**  Back-reference to the ASSETS.md section this rule encodes, e.g. `§2`. */
	specRef: string,
	production: Production,
	/**  Author-px width/height. `None` for procedural/runtime assets with no fixed size. */
	authorW: number | null,
	authorH: number | null,
	formats: Format[],
	nineSlice: Insets | null,
	/**  Whether the delivery checklist (§18) treats this as required. */
	required: boolean,
	/**  Human description carried into prompt generation (M2). */
	description: string,
};

/**
 *  Per-asset "draw a mark on a base" settings, persisted at `assets/<key>/glyph.json`.
 *  The base is just another asset in the game (e.g. `symbol_l_base` — an empty plate
 *  generated once through the normal flow); every symbol pointing at the same base
 *  gets a pixel-identical template.
 */
export type AssetGlyph = {
	/**  Asset key whose current best image is the shared template. */
	baseAsset: string,
	/**  What to draw on it — the glyph generation prompt. */
	prompt: string,
	/**  Library shape backing this mark, once generated. */
	glyphId?: string | null,
	transform: Transform,
	params: EmbossParams,
};

/**
 *  Broad asset category — drives which dist subdirectory it lands in and how the UI
 *  groups it.
 */
export type AssetKind = "symbol" | "background" | "reelChrome" | "symbolChrome" | "panel" | "payline" | "branding" | "splash" | 
/**  The on-screen character beside/above the reels (idle + reaction clips). */
"mascot" | 
/**  Transparent scene element that stacks over a plate at the same canvas. */
"sceneLayer" | 
/**  Standalone alpha set-piece object, not bound to the reel grid. */
"sceneSprite";

/**
 *  Per-asset working record: the prompt plus every generated variation. Canonical copy
 *  lives at `<project>/assets/<asset_key>/asset.json`.
 */
export type AssetRecord = {
	key: string,
	prompt: PromptState,
	variations?: Variation[],
	activeVariation?: string | null,
	/**
	 *  Template only (e.g. an `l_base` empty plate other symbols compose onto) —
	 *  excluded from Export and Publish; it never ships.
	 */
	templateOnly?: boolean,
};

export type Attachment = 
/**  Rigid quad of the part texture bound to the slot's bone. */
"region" | 
/**  Deformable mesh (Phase 7). */
{ mesh: MeshData };

/**  How the background of a generated image was produced — drives post-processing. */
export type BgMode = 
/**  Opaque scene (backgrounds/splash) — nothing to remove. */
"opaque" | 
/**  Native transparency (alpha already present) — nothing to remove. */
"native" | 
/**  Solid chroma-key colour to be removed by the `chromakey` stage. */
"chroma";

export type BlendMode = "normal" | "additive" | "multiply" | "screen";

/**
 *  A bone. `x`/`y` are the pivot in source pixels (y-down, world space — the emitter
 *  derives parent-local transforms). `rotation` is Spine-convention CCW degrees.
 */
export type Bone = {
	name: string,
	/**  `None` only for `root`. */
	parent: string | null,
	x: number | null,
	y: number | null,
	rotation: number | null,
	length: number | null,
	scaleX: number | null,
	scaleY: number | null,
};

export type BoneInfluence = {
	bone: string,
	weight: number | null,
};

/**
 *  One buy-bonus mode. Two or more of these unlock the buy-bonus selector screen
 *  (ASSETS.md §9).
 */
export type BuyBonusMode = {
	key: string,
	name: string,
};

/**  One chat turn (crosses the IPC boundary). */
export type ChatMessage = {
	role: string,
	content: string,
};

export type Clip = {
	id: string,
	/**  Animation name in the exported skeleton: `idle`, `win`, `expand`… */
	name: string,
	/**  Seconds. */
	duration: number | null,
	looping: boolean,
	timelines: Timeline[],
};

/**  Both compose outputs, on the same canvas. */
export type ComposedPreview = {
	image: string,
	mask: string,
	width: number,
	height: number,
};

export type ContactCell = {
	key: string,
	/**  Cell origin on the sheet, px. */
	x: number,
	y: number,
	/**  Post-fit ink fraction (0 when unknown). */
	inkPct: number | null,
	/**  "ok" | "underweight" | "overweight" | "missing" | "". */
	flag: string,
};

export type ContactSheet = {
	png: string,
	cellW: number,
	cellH: number,
	cols: number,
	rows: number,
	cells: ContactCell[],
};

export type Curve = "linear" | "stepped" | 
/**
 *  Normalized unit-square handles, 4 floats `(cx1, cy1, cx2, cy2)` per value component
 *  (so 4 for rotate/alpha, 8 for translate/scale). The emitter denormalizes to Spine
 *  4.x absolute time/value control points.
 */
{ bezier: (number | null)[] };

export type DepthStatus = { state: "missing" } | { state: "ready" };

/**  Emboss look controls. */
export type EmbossParams = {
	/**  Bevel width in px at base resolution. */
	depth: number | null,
	/**  Strength of the raised highlight toward the lower-left light (0–2). */
	highlight: number | null,
	/**  Strength of the soft shadow away from the light (0–2). */
	shadow: number | null,
	/**  Glyph fill tone relative to the base material (1 = untouched, <1 darker). */
	fillTone: number | null,
};

/**  Result of an export run, surfaced to the UI. */
export type ExportReport = {
	/**  Absolute path of the dist folder that was (re)built. */
	distPath: string,
	/**  Asset keys written to dist. */
	written: string[],
	/**  Required raster assets that have no processed active variation yet. */
	missing: string[],
	/**  Procedural / runtime / manual-tool assets handled outside this pipeline. */
	waived: string[],
	/**  The `assets.ts` manifest fragment (§17). */
	manifestSnippet: string,
};

export type FillStatus = {
	layerId: string,
	state: InpaintState,
};

/**
 *  Symbol fit rule: the eye reads INK (covered pixels), not height — a hat and a
 *  hand at equal height differ ~3× in ink and read as different pay classes. Each
 *  class blends a height-based scale with an ink-based scale (geometric mean,
 *  `area_weight` = the taste dial), anchors centroid-biased, and hard-clamps to the
 *  safe box so nothing overflows its cell.
 */
export type FitClass = {
	/**  Target ink as a fraction of cell area. */
	ink: number | null,
	/**  Target bbox height as a fraction of cell height (the blend's other pole). */
	height: number | null,
	/**  Acceptable |ink_after − ink| before the report flags UNDER/OVERWEIGHT. */
	tolerance: number | null,
};

/**  Output file formats an asset must ship in. */
export type Format = "webp" | "png" | "jpg" | 
/**  A `<name>.9.json` inset descriptor accompanies the raster (ASSETS.md §4). */
"nineSliceJson";

/**
 *  The full, generic game configuration that drives asset derivation. Nothing here is
 *  specific to any single game — Babewyn and a 5x3 lines game are just two instances.
 */
export type GameConfig = {
	/**  Folder-safe id, e.g. `babewyn_court`. */
	gameId: string,
	/**  Display name, e.g. "Babewyn Court". */
	name: string,
	/**  Free-form theme / art-direction brief for the whole game (documentation). */
	brief?: string,
	/**
	 *  The **style master**: the hand-authored aesthetic core prepended to every
	 *  asset prompt. This is the primary anti-slop lever — the studio owns it.
	 */
	stylePrompt?: string,
	/**
	 *  The **negative master**: hand-authored negatives applied to every asset
	 *  (suppresses the AI-slop tells). Falls back to a studio default if empty.
	 */
	negativePrompt?: string,
	winType: WinType,
	cols: number,
	rows: number,
	symbols: SymbolDef[],
	/**  Whether the game ships a distinct feature/free-spins background (ASSETS.md §3). */
	hasFeatureBackground?: boolean,
	/**  Whether a buy-bonus button is shown (ASSETS.md §9 `button_buy_bonus`). */
	hasBuyBonus?: boolean,
	/**  Buy-bonus modes; `len() >= 2` unlocks the selector screen. */
	buyBonusModes?: BuyBonusMode[],
	/**  Feature-collection meter mechanic (ASSETS.md §9 meter block). */
	hasMeter?: boolean,
	meterThresholds?: number,
	/**  Mystery-symbol mechanic (ASSETS.md §5/§6). */
	hasMystery?: boolean,
	/**  Hold-and-spin mechanic (ASSETS.md §5 `symbol_hold_indicator`). */
	holdAndSpin?: boolean,
	/**  On-screen mascot character beside/above the reels (ASSETS.md §10 feature hero). */
	hasMascot?: boolean,
	/**  Who the mascot is — flows into the generation prompt as the subject. */
	mascotDescription?: string,
	/**  Visual-mass sizing targets for symbols (Process normalizes to these). */
	symbolSizing?: SymbolSizing,
	/**  Default provider id for SYMBOL generation ("" = whatever the bench has selected). */
	symbolProvider?: string,
	/**  Scene-asset system: plates / layers / set-piece sprites with composition guides. */
	scene?: SceneConfig,
};

/**
 *  One reusable shape in the cross-game library. The shape itself lives next to this
 *  meta as `shape.png` (white fill, alpha = the mark, cropped with a small margin).
 */
export type GlyphInfo = {
	id: string,
	name: string,
	/**  The prompt the shape was generated from (empty for imports). */
	prompt: string,
	createdAt: number | null,
};

/**
 *  A named set of zones bound to one preset (e.g. "hud_landscape": reel frame block,
 *  HUD top/bottom bands, portrait-surviving centre strip, safe margins).
 */
export type GuideTemplate = {
	key: string,
	/**  Preset these zones lay over. */
	preset: string,
	zones?: GuideZone[],
};

/**
 *  One labeled composition zone, in PERCENT of the canvas (0–100) — simple enough to
 *  type by hand straight from a runtime real-estate report.
 */
export type GuideZone = {
	label: string,
	x: number | null,
	y: number | null,
	w: number | null,
	h: number | null,
};

export type InpaintState = 
/**  Nothing occludes this part — no inpaint needed. */
"clear" | 
/**  Occluded, no completed texture yet. */
"pending" | 
/**  Completed texture matches the current masks. */
"fresh" | 
/**  Masks changed since the completed texture was generated. */
"stale";

export type InpaintStatus = {
	partId: string,
	state: InpaintState,
};

/**  9-slice border insets in author px on the source raster (ASSETS.md §4). */
export type Insets = {
	top: number,
	right: number,
	bottom: number,
	left: number,
};

export type Key = {
	time: number | null,
	/**  1 value (rotate/alpha) or 2 (translate/scale). */
	v: (number | null)[],
	/**  Ease OUT of this key toward the next. */
	curve?: Curve,
};

export type Layer = {
	/**  Slug id — also the on-disk dir and export file name. */
	id: string,
	name: string,
	/**  SAM seed prompts, normalized 0..1 (empty for the catch-all). */
	prompts?: SamPrompt[],
	/**
	 *  sha256 of the author mask PNG; `None` for the catch-all layer (index 0), whose
	 *  geometry hash is derived from the masks above it at cut time.
	 */
	maskHash?: string | null,
	/**  Tight bbox of `cut.png` in source coords; `None` until cut. */
	bbox?: Rect | null,
	/**  Fill cache key (8-hex) of `filled.<h>.png`; `None` = not filled. */
	filledHash?: string | null,
	filledBbox?: Rect | null,
	/**
	 *  Parallax multiplier: 0 = pinned to the camera (infinite distance), 1 = moves with
	 *  the play field. Foregrounds may exceed 1 slightly.
	 */
	speed: number | null,
};

export type LayerProposal = {
	id: string,
	name: string,
	/**  SAM seed prompts, normalized 0..1. Empty for the farthest (catch-all) layer. */
	points: SamPrompt[],
	/**  Suggested parallax multiplier, monotonically increasing with nearness. */
	speed: number | null,
};

export type LayerSettings = {
	/**  Maximum camera offset the game will apply, in source px (drives fill band width). */
	maxShiftPx?: number,
	/**
	 *  Duplicated seam band under nearer layers (px). Motion is guaranteed for parallax,
	 *  so this defaults wider than the studio's 3.
	 */
	seamFringe?: number,
	/**  Explicit fill band radius override (px); 0 = derive per layer from speed deltas. */
	bandPx?: number,
};

export type LayersDoc = {
	version: number,
	source: SourceRef,
	/**  Back → front. Index 0 is the catch-all (no mask). */
	layers: Layer[],
	settings?: LayerSettings,
	updatedAt: number | null,
};

export type LayersExportReport = {
	/**  Written files (relative to the export dir), back → front. */
	files: string[],
	/**  Layers exported from a stale or missing fill (raw cut used instead). */
	stale: string[],
	width: number,
	height: number,
};

/**  A candidate mask for one part, previewed in the UI before the user accepts it. */
export type MaskResult = {
	/**  Full-source-size 0/255 gray PNG as a data URL. */
	maskDataUrl: string,
	/**  Set pixels (post-refinement). */
	area: number,
	bbox: Rect | null,
};

/**
 *  Outcome of the symbol FIT pass. `clamped_by` names which limit fired; `flag`
 *  reports UNDER/OVERWEIGHT vs the class tolerance — an art problem to surface, not
 *  silently fudge (the object needs a base, mount or bracket at generation time).
 */
export type MassReport = {
	/**  Ink fraction of the cell actually reached after the fit. */
	achieved: number | null,
	/**  The class's configured ink target. */
	target: number | null,
	/**  True when a clamp fired (box or placement). */
	clamped: boolean,
	/**  "none" | "box" | "placement". */
	clampedBy?: string,
	/**  Ink fraction before the fit. */
	inkBefore?: number | null,
	/**  The two candidate scales and the blended, clamped result. */
	scaleHeight?: number | null,
	scaleArea?: number | null,
	scaleFinal?: number | null,
	/**  "ok" | "underweight" | "overweight" vs the class tolerance. */
	flag?: string,
	/**  scale_final > 1.15 — the source lacks resolution, regenerate larger. */
	upscaled?: boolean,
};

export type MeshData = {
	/**  Vertex positions in source pixels, 2 floats per vertex. */
	vertices: (number | null)[],
	/**  0..1 within the part texture, 2 per vertex. */
	uvs: (number | null)[],
	triangles: number[],
	hull: number,
	/**  Per-vertex bone influences; `None` = bind rigidly to the slot bone. */
	weights?: VertexWeights[] | null,
};

export type PageImage = {
	/**  File name the atlas text references, e.g. `symbol_h1.webp`. */
	name: string,
	/**  `data:image/webp;base64,…` for direct loading in the webview. */
	dataUrl: string,
};

export type Part = {
	/**  Slug id: `head`, `left_arm`… Also the atlas region + attachment name. */
	id: string,
	name: string,
	/**  SAM click prompts that produced the current mask (re-runnable). */
	prompts?: SamPrompt[],
	/**  Bounding box of `cut.png` within the source image; `None` until cut. */
	bbox?: Rect | null,
	/**  sha256 of `mask.png` — drives inpaint invalidation. */
	maskHash?: string | null,
	/**  Which `completed.<hash8>.png` is current, if inpainted. */
	completedHash?: string | null,
	/**  Bbox of the completed texture (it extends past `bbox` into the hidden band). */
	completedBbox?: Rect | null,
	/**  Which file feeds the atlas: the raw cut or the inpaint-completed texture. */
	texture?: PartTexture,
};

export type PartProposal = {
	/**  Slug id (also bone/slot/region name), e.g. `head`, `left_arm`. */
	id: string,
	name: string,
	/**  SAM seed prompts, normalized 0..1. */
	points: SamPrompt[],
};

export type PartTexture = "cut" | "completed";

/**
 *  A Spine 4.2 physics constraint on one bone. Defaults make a pleasant rotational sway
 *  for chain segments (crests, capes, pendants); the runtime computes the motion from how
 *  the bone's parent moves — no keyframes.
 */
export type PhysicsSpec = {
	bone: string,
	/**  How much physics drives the bone's rotation (0..1). */
	rotate?: number | null,
	/**  How much prior momentum carries over (0..1). Higher = floatier. */
	inertia?: number | null,
	/**  Spring pull back toward the pose. Higher = stiffer. */
	strength?: number | null,
	/**  Velocity decay per step (0..1). Lower = wobbles longer. */
	damping?: number | null,
	/**  Constant sideways force (world units/sec). */
	wind?: number | null,
	/**  Constant downward force (world units/sec). */
	gravity?: number | null,
	/**  Blend between posed and physical result (0..1). */
	mix?: number | null,
};

/**  Which external tools are available. */
export type Preflight = {
	/**  `rembg` CLI present (background removal). */
	rembg: boolean,
	/**  Real-ESRGAN upscaler present. */
	upscale: boolean,
	/**  Resolved path of the upscaler binary, if found. */
	upscaleBin: string | null,
};

export type PreviewBundle = {
	skeletonJson: string,
	atlasText: string,
	pages: PageImage[],
};

/**
 *  How an asset is produced. Only `Raster` assets flow through the generation loop;
 *  the rest are handled in code / at runtime and are surfaced as "waived" in the UI.
 *  (ASSET_SOURCING flags procedural-vs-raster per asset.)
 */
export type Production = 
/**  Generatable image (goes through providers + post-processing). */
"raster" | 
/**  Drawn in code with PIXI at runtime (paylines, cluster outlines, win glow). */
"procedural" | 
/**  Rendered from a bitmap font at runtime. */
"runtimeFont" | 
/**  Requires an external authoring tool (e.g. 9-slice measured by hand, Spine). */
"manualTool";

/**
 *  A persisted project: the game config plus project-level metadata. Canonical copy
 *  lives at `<projects_root>/<game_id>/project.json`.
 */
export type Project = {
	schemaVersion: number,
	config: GameConfig,
	/**  Unix epoch milliseconds. */
	createdAt: number | null,
	/**  Unix epoch milliseconds. */
	updatedAt: number | null,
	/**
	 *  Last folder the game's finished assets were published to (remembered for one-click
	 *  re-publish). Absolute path.
	 */
	publishDir?: string | null,
};

/**  Lightweight listing entry for the projects picker. */
export type ProjectSummary = {
	gameId: string,
	name: string,
	updatedAt: number | null,
	symbolCount: number,
};

/**
 *  The editable prompt state for one asset. Persisted in `assets/<key>/asset.json`.
 * 
 *  Prompts are assembled deterministically from the game's style master + a per-category
 *  composition template + this per-asset `subject`. No LLM is involved. Power users can
 *  bypass assembly with a full `override`.
 */
export type PromptState = {
	/**  The variable part: what this asset actually is (a short phrase). */
	subject?: string,
	/**  Optional full-prompt override — if non-empty, used verbatim instead of assembly. */
	overridePrompt?: string,
	/**  Optional per-asset negative override. */
	negativeOverride?: string,
	/**
	 *  Backgrounds only: the scene will be cut into parallax depth layers, so the prompt
	 *  asks for cleanly separable planes (crisp silhouettes, no cross-plane haze/blur).
	 */
	layered?: boolean,
	/**  Unix epoch millis of the last change. */
	updatedAt?: number | null,
};

/**  What a provider supports, surfaced to the UI. */
export type ProviderInfo = {
	id: string,
	displayName: string,
	supportsSeed: boolean,
	nativeAlpha: boolean,
	/**  Whether style-reference images can be attached to generations. */
	supportsRefs: boolean,
	/**  Whether the provider is ready to use (key present / endpoint configured). */
	configured: boolean,
};

/**  Result of a publish run. */
export type PublishReport = {
	dest: string,
	/**  Asset keys whose `<key>.webp` + secondary twin were copied. */
	copied: string[],
	skipped: PublishSkip[],
};

/**  One asset that couldn't be published, with why. */
export type PublishSkip = {
	key: string,
	reason: string,
};

export type QualityCheck = {
	id: string,
	label: string,
	/**  "pass" | "warn" | "fail" */
	status: string,
	detail: string,
};

export type QualityReport = {
	checks: QualityCheck[],
	/**  warn + fail count (the badge number). */
	issues: number,
};

export type Rect = {
	x: number,
	y: number,
	w: number,
	h: number,
};

export type SamLabel = "positive" | "negative";

/**  A SAM point prompt, normalized 0..1 over the source image. */
export type SamPrompt = {
	x: number | null,
	y: number | null,
	label: SamLabel,
};

export type SamStatus = 
/**  Weights not downloaded yet; segmentation falls back to manual masks. */
{ state: "missing" } | 
/**  `model` is "tiny" (MobileSAM) or "vit_b" (full SAM — better masks). */
{ state: "ready"; path: string; model: string };

/**  A scene asset: one shared prompt core plus linked variants managed as a group. */
export type SceneAssetDef = {
	/**  Base key; variants derive `<key>_<variant>` (e.g. `bg_base` → `bg_base_landscape`). */
	key: string,
	kind: SceneKind,
	name?: string,
	/**  Shared prompt core — what this scene asset IS, across every variant. */
	description?: string,
	/**  Provider override for this asset ("" → the scene class default). */
	provider?: string,
	/**
	 *  The element has interior see-through openings (window glass, arch gaps): they
	 *  are generated as flat chroma fills and keyed to real transparency by Process.
	 */
	cutouts?: boolean,
	/**
	 *  The texture must tile seamlessly in the HORIZONTAL direction (panning cloud
	 *  band): adds the tileable prompt clause + the seam check in the bench.
	 */
	wrap?: boolean,
	/**  Runtime placement for the scene manifest (None → asset omitted from scene.json). */
	placement?: ScenePlacement | null,
	variants?: SceneVariantDef[],
};

/**  Per-project scene system config. */
export type SceneConfig = {
	presets?: ScenePreset[],
	guides?: GuideTemplate[],
	assets?: SceneAssetDef[],
	/**  Default provider id for the scene class ("" = whatever the bench has selected). */
	defaultProvider?: string,
	/**  WebP quality for scene exports (10–100). */
	webpQuality?: number,
};

/**  Scene-asset sub-types. Symbols are square grid cutouts; scene art is not. */
export type SceneKind = 
/**  Full-frame opaque background at a fixed preset resolution. */
"plate" | 
/**
 *  Transparent element that stacks over a plate at the SAME canvas (e.g. the storm
 *  sky seen inside a window arch) — generated and exported with alpha.
 */
"layer" | 
/**  Standalone alpha object not bound to the reel grid (e.g. an observation booth). */
"sprite" | 
/**  Effect still meant to become a short looping spritesheet (flame, steam, arc). */
"fx" | 
/**  Tiny single-sprite alpha texture for the particle system (rain streak, dust mote). */
"particle";

/**
 *  Placement metadata for the runtime scene manifest (`scene.json`). Contract owned by
 *  the game runtime: normalized 0–1 canvas coordinates, anchor is a pivot within the
 *  texture, z-order = manifest array order, parallax is a 0–1 depth multiplier
 *  (back ≈ 0.05, mid ≈ 0.3, foreground ≈ 0.8) — code owns the drift amplitude.
 */
export type ScenePlacement = {
	/**
	 *  "cover" (full-bleed) | "anchored" (set-piece). Empty → cover for plates/layers,
	 *  anchored for sprites/fx/particles.
	 */
	fit?: string,
	/**  Pivot within the texture, [x, y] 0–1 (default center; [0.5, 1] = floor-standing). */
	anchor?: (number | null)[] | null,
	/**  Where the anchor lands, [x, y] normalized 0–1 of the live canvas. */
	pos?: (number | null)[] | null,
	/**  Sprite height as a fraction of canvas height (width follows aspect). Anchored only. */
	height?: number | null,
	/**  Depth multiplier 0–1. */
	parallax?: number | null,
	/**  Cover oversize so parallax never reveals an edge (cover only, e.g. 0.08). */
	overscan?: number | null,
	/**  Optional blend mode: "" (normal) | "add" | "screen". */
	blend?: string,
	/**  fx only: playback rate; the runtime converts to animationSpeed. */
	fps?: number | null,
	/**  fx only: whether the clip loops. */
	loop?: boolean | null,
};

/**  A named fixed resolution that plates/layers generate and export at. */
export type ScenePreset = {
	key: string,
	width: number,
	height: number,
};

/**
 *  One variant of a scene asset along the orientation/state axes ("landscape",
 *  "portrait", "feature_landscape", "tempest"…). Derived asset key = `<asset>_<variant>`.
 */
export type SceneVariantDef = {
	key: string,
	/**
	 *  Preset for plates/layers ("" → the project's first preset). Sprites may leave it
	 *  empty for a square canvas.
	 */
	preset?: string,
	/**  Appended to the asset's shared prompt core for this variant only. */
	extraPrompt?: string,
	/**
	 *  Placement OVERRIDES for this variant (shallow-merged over the asset's placement
	 *  in the manifest; variants named "portrait"/"tablet" emit as manifest overrides).
	 */
	placement?: ScenePlacement | null,
};

/**  The assembled sheet prompt, shown to the user BEFORE generating — editable. */
export type SetPlan = {
	positive: string,
	negative: string,
	cols: number,
	rows: number,
	cells: SetPlanCell[],
};

export type SetPlanCell = {
	assetKey: string,
	label: string,
};

/**
 *  A generated (but not yet cut) sheet: preview + where the cuts will land.
 *  Seams are fractions of the sheet's width/height (internal boundaries only).
 */
export type SetSheet = {
	png: string,
	cols: number,
	rows: number,
	seamsX: (number | null)[],
	seamsY: (number | null)[],
};

export type Slot = {
	/**  Slot name; `== part_id` by convention. */
	name: string,
	bone: string,
	partId: string,
	attachment?: Attachment,
	/**
	 *  Spine blend mode. `Additive` is the light-effect mode: black adds nothing, so FX
	 *  layers generated on black become pure light.
	 */
	blend?: BlendMode,
};

/**  Which processed variation the studio source was snapshotted from. */
export type SourceRef = {
	variationId: string,
	width: number,
	height: number,
	/**  sha256 of `source.png` — gates the SAM embedding and inpaint caches. */
	sha256: string,
};

/**  One produced stage file (relative to the variation dir). */
export type StageOutput = {
	name: string,
	file: string,
};

export type StudioDoc = {
	/**  Document schema version, for future migrations. */
	version: number,
	source: SourceRef,
	/**  Draw order = index (0 = drawn first, i.e. behind). */
	parts: Part[],
	/**  Flattened bone tree; parent by name; index 0 is always `root`. */
	bones: Bone[],
	/**  One slot per part (usually); array order mirrors `parts` draw order. */
	slots: Slot[],
	/**
	 *  Spine 4.2 physics constraints — the RUNTIME simulates these (dangle/sway with
	 *  inertia), no keyframes involved.
	 */
	physics?: PhysicsSpec[],
	clips: Clip[],
	settings?: StudioSettings,
	/**
	 *  The planned animation, described BEFORE cutting — it steers the auto-cut
	 *  (every element that moves on its own becomes its own part) and seeds the AI
	 *  clip brief later. Seeded from the Blueprint's per-symbol animation note.
	 */
	motionBrief?: string,
	updatedAt: number | null,
};

export type StudioExportReport = {
	dir: string,
	files: string[],
	warnings: string[],
};

export type StudioSettings = {
	/**  Timeline display fps (playback is continuous; this is snapping granularity). */
	fps: number,
	/**  Default inpaint band radius in px (0 = auto per part). */
	bandRadius: number | null,
	onionBefore: number,
	onionAfter: number,
	/**
	 *  Pixels of duplicated boundary a part keeps UNDER its covering neighbours when cut.
	 *  Hides razor seams the moment parts move (the classic cutout-artist trick). 0 = off.
	 */
	seamFringe?: number,
};

/**  One symbol declared in the game config. The taxonomy expands one asset per entry. */
export type SymbolDef = {
	/**  Stable slug used to build the asset key, e.g. `h1`, `l3`, `wild`, `ink_drop`. */
	key: string,
	role: SymbolRole,
	/**  Human display name, e.g. "Snail-Knight". Feeds prompt generation (M2). */
	name: string,
	/**  Art-direction notes for this symbol. Feeds prompt generation (M2). */
	description?: string,
	/**
	 *  Intended motion, one short sentence — seeds AI spritesheet / motion drafting.
	 *  Spritesheet animations cap at 24 frames (~2 s loop), so keep it loopable.
	 */
	animation?: string,
	/**
	 *  Manual scale multiplier layered ON TOP of the visual-mass rule (1 = neutral).
	 *  The hard extent clamp still applies.
	 */
	sizeNudge?: number | null,
};

/**
 *  A symbol's tier/role. Drives cardinality (one asset per symbol) and the oversize
 *  exception for wild/scatter (ASSETS.md §2 Step 5).
 */
export type SymbolRole = "high" | "low" | "wild" | "scatter" | "bonus" | 
/**
 *  Mechanic-specific special symbol (e.g. an ink drop / multiplier orb). No-pay,
 *  standard cell size, but still a generatable raster.
 */
"special" | 
/**
 *  A wild that EXPANDS to cover its reel: derives TWO assets — the normal
 *  cell-sized `symbol_<key>` plus a full-column `symbol_<key>_expanded` twin
 *  (fit pass skipped, full-height composition).
 */
"expandingWild";

export type SymbolSizing = {
	low?: FitClass,
	high?: FitClass,
	wild?: FitClass,
	scatter?: FitClass,
	/**
	 *  0 = pure height fit (the old broken behaviour), 1 = pure ink fit (comically
	 *  large slim objects). Geometric blend between the two scales.
	 */
	areaWeight?: number | null,
	/**
	 *  Anchor = bias·centroid + (1−bias)·bbox centre. Pure bbox sits base-heavy
	 *  objects low; pure centroid pushes wide-topped objects out of the safe box.
	 */
	centroidBias?: number | null,
	/**  Alpha below this (0–255) is chroma fringe / glow haze — not ink. */
	alphaFloor?: number,
	/**  The bbox may never exceed these fractions of the cell. */
	safeW?: number | null,
	safeH?: number | null,
	/**
	 *  Fixed square output canvas in px. 0 = keep the source canvas/resolution
	 *  (today's shipping behaviour); e.g. 512 for fixed game cells (2× the ~228 px
	 *  largest real cell).
	 */
	canvas?: number,
};

export type Timeline = {
	target: TimelineTarget,
	/**  Sorted by time ascending. */
	keys: Key[],
};

export type TimelineTarget = 
/**  Degrees, offset from setup pose. */
({ boneRotate: string }) & { boneScale?: never; boneTranslate?: never; slotAlpha?: never } | 
/**  Pixels (source scale), offset from setup pose. `v = [x, y]`. */
({ boneTranslate: string }) & { boneRotate?: never; boneScale?: never; slotAlpha?: never } | 
/**  Multiplier of setup scale. `v = [x, y]`. */
({ boneScale: string }) & { boneRotate?: never; boneTranslate?: never; slotAlpha?: never } | 
/**  Absolute alpha 0..1 on a slot. */
({ slotAlpha: string }) & { boneRotate?: never; boneScale?: never; boneTranslate?: never };

/**  Where a glyph sits on the base. */
export type Transform = {
	/**  Glyph centre as a fraction of the base width (0.5 = centred). */
	x: number | null,
	/**  Glyph centre as a fraction of the base height. */
	y: number | null,
	/**  Glyph long side as a fraction of the base's shorter side. */
	scale: number | null,
	/**  Degrees, clockwise. */
	rotation: number | null,
};

/**  A single generated image variation and its full lineage (M3 fills this in). */
export type Variation = {
	id: string,
	/**  The variation this one branched from (retry / vary), if any. */
	parent?: string | null,
	createdAt: number | null,
	/**  Exact prompt text used for this generation. */
	promptSnapshot: string,
	/**  Provider id, e.g. `drawthings` / `openai_image`. */
	provider: string,
	/**  Model within the provider, if known. */
	model?: string | null,
	seed?: number | null,
	/**  Relative path (from the asset dir) of the raw generated image. */
	rawFile: string,
	status: VariationStatus,
	/**  How the background was generated (drives post-processing bg removal). */
	background?: BgMode,
	/**  Post-processing stage outputs (paths relative to the variation dir). */
	stages?: StageOutput[],
	/**  Visual-mass sizing outcome from the last Process run (symbols only). */
	massReport?: MassReport | null,
	/**  Locked/favourited — protected from history pruning (`delete_variation` refuses it). */
	locked?: boolean,
};

export type VariationStatus = "generating" | "ready" | "failed";

export type VertexWeights = {
	influences: BoneInfluence[],
};

/**
 *  The pay system, which gates several asset categories (paylines vs way-indicator
 *  vs cluster-outline) per ASSETS.md §8.
 */
export type WinType = "lines" | "ways" | "scatter" | "cluster";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

